name: Build and release GatewayD

on:
  release:
    types: [published]
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go 1.19
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
          cache: true
      - run: go mod tidy
      - name: Generate CycloneDX SBOM artifacts
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        run: |
          go install github.com/CycloneDX/cyclonedx-gomod/cmd/cyclonedx-gomod@latest
          cyclonedx-gomod mod -json -licenses -output code-cyclonedx-gatewayd-${{ github.ref_name }}.json
      - name: Build and release binaries with goreleaser
        uses: goreleaser/goreleaser-action@v2
        if: success() && startsWith(github.ref, 'refs/tags/')
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GORELEASER_CURRENT_TAG: ${{ github.ref }}
          GORELEASER_RELEASE_NOTES: ${{ github.event.release.body }}
